import { Inter } from "next/font/google";
import "./globals.css";
import { Navigation } from "../components/layout/Navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Ableton",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="flex row gap-8 px-8 py-4 align-middle">
          <div className="w-16">
            <img src="./ableton-logo.png" alt="" className="object-contain" />
          </div>
          <span className="text-lg">Live</span>
          <span className="text-lg">Push</span>
          <span className="text-lg">Shop</span>
          <span className="text-lg">Packs</span>
          <span className="text-lg">Help</span>
        </div>
      </body>
    </html>
  );
};
